if (table_type == "latex"){
  theme_update(
    #   line = element_line(),
    #   rect = element_rect(),
    #   text = element_text(),
    #   axis.text = element_text(),
    #   strip.text = element_text(),
    #   axis.line = element_blank(),
    axis.text.x = element_text(family = "PT Sans", face = "plain", colour = "black",
                               size = 10, hjust = 1, vjust = 1, angle = 0,
                               lineheight = 0.8, inherit.blank=TRUE),
    axis.text.y = element_text(family = "PT Sans", face = "plain", colour = "black",
                               size = 10, hjust = 1, vjust = 0.5, angle = 0,
                               lineheight = 0.8, inherit.blank=TRUE),
    axis.ticks = element_blank(),
    axis.title.x = element_text(family = "PT Sans", 
                                colour = "black",
                                size = 10, 
                                hjust = 0.5,
                                # vjust = 0.9, obsolete
                                face = "plain",
                                angle = 0,
                                lineheight = 0.7, inherit.blank=TRUE),
    axis.title.y = element_text(family = "PT Sans",
                                # face = "plain",
                                colour = "black",
                                size = 10, 
                                hjust = 0.5,
                                # vjust = 0.9, obsolete
                                face = "plain",
                                angle = 90,
                                lineheight = 0.7, inherit.blank=TRUE),
    #   axis.ticks.length = ,
    #   axis.ticks.margin = ,
    legend.background = element_blank(),
    #   legend.margin = ,
    legend.key = element_rect(fill = NA, colour = NA),
    #   legend.key.size = ,
    #   legend.key.height = NULL,
    #   legend.key.width = NULL,
    legend.text = element_text(size = 10, lineheight = 0.7),
    #   legend.text.align = NULL,
    legend.title = element_blank(),
    #   legend.title.align = NULL,
    legend.position = "top",
    legend.direction = "horizontal",
    legend.key.height = unit(4,"mm"),
    legend.key.width = unit(4,"mm"),
    #   legend.justification = "center",
    legend.box = NULL,
    #   panel.background = element_rect(fill = col.main3, colour = col.main3,
    #                                   size = NULL, linetype = NULL),
    panel.background = element_blank(),
    panel.border = element_blank(),
    # panel.grid.major = element_line(colour = col.main2, size = 0.5),
    panel.grid.major.x = element_line(colour = "grey80", size = 0.5),
    panel.grid.major.y = element_blank(),
    panel.grid.minor = element_blank(),
    #   panel.margin = ,
    strip.background = element_rect(colour = "transparent", fill = "transparent",
                                    size = NULL, linetype = NULL),
    #   strip.text.x = element_text(),
    #   strip.text.y = element_text(),
    #   plot.background = element_rect(fill = col.main2, colour = col.main2,
    #                                  size = NULL, linetype = NULL),
    plot.background = element_blank(),
    #plot.background = element_rect(fill=NA,colour = "grey90",size=1,linetype="solid"),
    plot.title =  element_blank(),
    plot.margin = unit(rep(0.1, 4), "line")
    
    
  )
  
  space <- function(x, ...) { 
    format(x, ..., big.mark = " ", scientific = FALSE, trim = TRUE)
  }
} else {
  theme_update(
    #   line = element_line(),
    #   rect = element_rect(),
    #   text = element_text(),
    #   axis.text = element_text(),
    #   strip.text = element_text(),
    #   axis.line = element_blank(),
    axis.text.x = element_text(family = "PT Sans", face = "plain", colour = "black",
                               size = 14, hjust = 1, vjust = 1, angle = 0,
                               lineheight = 0.8, inherit.blank=TRUE),
    axis.text.y = element_text(family = "PT Sans", face = "plain", colour = "black",
                               size = 14, hjust = 1, vjust = 0.5, angle = 0,
                               lineheight = 0.8, inherit.blank=TRUE),
    axis.ticks = element_blank(),
    axis.title.x = element_text(family = "PT Sans", face = "plain", colour = "black",
                                size = 14, hjust = 0.5, vjust = 0.2, angle = 0,
                                lineheight = 0.7, inherit.blank=TRUE),
    axis.title.y = element_text(family = "PT Sans", face = "plain", colour = "black",
                                size = 14, hjust = 0.5, vjust = 0.2, angle = 90,
                                lineheight = 0.7, inherit.blank=TRUE),
    #   axis.ticks.length = ,
    #   axis.ticks.margin = ,
    legend.background = element_blank(),
    #   legend.margin = ,
    legend.key = element_rect(fill = NA, colour = NA),
    #   legend.key.size = ,
    #   legend.key.height = NULL,
    #   legend.key.width = NULL,
    legend.text = element_text(size = 14, lineheight = 0.7),
    #   legend.text.align = NULL,
    legend.title = element_blank(),
    #   legend.title.align = NULL,
    legend.position = "top",
    legend.direction = "horizontal",
    legend.key.height = unit(7,"mm"),
    legend.key.width = unit(7,"mm"),
    #   legend.justification = "center",
    legend.box = NULL,
    #   panel.background = element_rect(fill = col.main3, colour = col.main3,
    #                                   size = NULL, linetype = NULL),
    panel.background = element_blank(),
    panel.border = element_blank(),
    # panel.grid.major = element_line(colour = col.main2, size = 0.5),
    panel.grid.major.x = element_line(colour = "grey80", size = 0.5),
    panel.grid.major.y = element_blank(),
    panel.grid.minor = element_blank(),
    #   panel.margin = ,
    strip.background = element_rect(colour = "transparent", fill = "transparent",
                                    size = NULL, linetype = NULL),
    #   strip.text.x = element_text(),
    #   strip.text.y = element_text(),
    #   plot.background = element_rect(fill = col.main2, colour = col.main2,
    #                                  size = NULL, linetype = NULL),
    plot.background = element_blank(),
    #plot.background = element_rect(fill=NA,colour = "grey90",size=1,linetype="solid"),
    plot.title =  element_blank(),
    plot.margin = unit(rep(0.1, 4), "line")
    
    
  )
  
  space <- function(x, ...) { 
    format(x, ..., big.mark = " ", scientific = FALSE, trim = TRUE)
  }
}

