---
title: FAO Statistical pocketbooks - works in progress
author: Markus Kainu
date: "Last updated: **`r Sys.time()`**"
output: 
  html_document: 
    toc: true
    toc_float: true
    number_sections: yes
    code_folding: hide
    theme: united
---



<div class="alert alert-dismissible alert-warning">
  <button type="button" class="close" data-dismiss="alert">&times;</button>
  <h4>Read this!</h4>
  <p>TESTED WITH LATEST FIREFOX BROWSER, TRY USING IT IF PROBLEMS</p>
</div>

# Current pdfs


```{r, include=FALSE}
library(tidyverse)
library(pdftools)
root.dir <- "~/faosync/pocketbooks/pocketbook/"

# boooks <- list.files(path = paste0(root.dir,"/output/pdf/"), pattern = ".pdf", full.names = TRUE)
books <- c("GLO", "RAF", "RAP", "REU", "REU_ru", "RNE","COF")
pdfinfodata <- data_frame()
for (book in books){
  path <- paste0(root.dir,"/output/pdf/syb_main_",book,".pdf")
  if (!file.exists(path)) next()
  newline <- as.data.frame(pdf_info(path)[c("modified","pages")])
  newline$book <- book
  pdfinfodata <- bind_rows(pdfinfodata,newline)
}
```

| link to pdf | Modified | pages |
| --- | -------- | ----- |
| [GLO](pdf/syb_main_GLO.pdf) | ``r pdfinfodata %>% filter(book %in% "GLO") %>% .$modified`` | ``r pdfinfodata %>% filter(book %in% "GLO") %>% .$pages``|
| [REU](pdf/syb_main_REU.pdf) | ``r pdfinfodata %>% filter(book %in% "REU") %>% .$modified`` | ``r pdfinfodata %>% filter(book %in% "REU") %>% .$pages``|
| [REU_ru](pdf/syb_main_REU_ru.pdf) | ``r pdfinfodata %>% filter(book %in% "REU_ru") %>% .$modified`` | ``r pdfinfodata %>% filter(book %in% "REU_ru") %>% .$pages``|
| [RAP](pdf/syb_main_RAP.pdf) | ``r pdfinfodata %>% filter(book %in% "RAP") %>% .$modified`` | ``r pdfinfodata %>% filter(book %in% "RAP") %>% .$pages``|
| [RAF](pdf/syb_main_RAF.pdf) | ``r pdfinfodata %>% filter(book %in% "RAF") %>% .$modified`` | ``r pdfinfodata %>% filter(book %in% "RAF") %>% .$pages``|
| [RNE](pdf/syb_main_RNE.pdf) | ``r pdfinfodata %>% filter(book %in% "RNE") %>% .$modified`` | ``r pdfinfodata %>% filter(book %in% "RNE") %>% .$pages``|
| [Coffee](pdf/syb_main_COF.pdf) | ``r pdfinfodata %>% filter(book %in% "COF") %>% .$modified`` | ``r pdfinfodata %>% filter(book %in% "COF") %>% .$pages``|

# Comparisons

- [Global 2015 vs. Global 2016](pdf/GLO15_GLO.html)
- [RAP 2016 vs. Global 2016](pdf/RAP.html)
- [REU 2016 vs. Global 2016](pdf/REU.html)
- [REU ru 2016 vs. Global 2016](pdf/REU_ru.html)
- [RNE 2016 vs. Global 2016](pdf/RNE.html)
- [RAF 2016 vs. Global 2016](pdf/RAF.html)
- [All regional books](pdf/regional_books16.html)
- [All 2016 books](pdf/all_books16.html)
- [REU vs. Reu ru](pdf/REU_ru_REU.html)
- [Country profiles](pdf/country_profiles.html)


# Data sources

- [Faostat](http://www.fao.org/faostat/en/#home)
- [World Development Indicators](http://data.worldbank.org/data-catalog/world-development-indicators)
- [ILO](http://www.ilo.org/ilostat/faces/ilostat-home/download?_adf.ctrl-state=xh99k169b_4&_afrLoop=54910682937899#!)

# Source code

- [pocketbook](https://github.com/UNFAOstatistics/pocketbook/)
- [pocketbook_database](https://github.com/UNFAOstatistics/pocketbook_database/)


# Data

- [all faostat in single csv (first 1000 lines)](data/faostat.csv) - *original has 72 million rows, 7,2 GB as .csv*
- [metadata for the above](data/meta_faostat.csv)
- [country level indicators for the book before aggregation](data/data_for_book.csv)


# misc

- [working hours](http://software.markuskainu.fi/fao/timesheet/fao_working_hours.html)